name: "ddd"
port: "8080"
alarm_email: ""

repo:
  mysql:
    writer:
      user: "writer"
      password: "1234"
      host: "localhost"
      port: "3306"
    reader:
      user: "reader"
      password: "1234"
      host: "localhost"
      port: "3307"
  redis:
    user: ""
    password: ""
    address: "localhost:6379"
  elasticsearch:
    user: ""
    password: ""
    host: "localhost"
    port: "9200"
    ca_path: ""
  kafka:
    user: ""
    password: ""
    host: "localhost"
    port: ""